# Generated by Django 5.2.1 on 2025-05-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(choices=[('direct', 'MariaDB/MySQL (TCP/IP)'), ('ssh', 'MariaDB/MySQL (SSH Tunnel)')], max_length=10)),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=3306)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('ssh_hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_port', models.IntegerField(blank=True, default=22, null=True)),
                ('ssh_username', models.CharField(blank=True, max_length=100, null=True)),
                ('ssh_password', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_key_file', models.FileField(blank=True, null=True, upload_to='ssh_keys/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
