# Generated by Django 5.2.1 on 2025-05-13 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0002_databaseserver_last_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Codziennie'), ('weekly', 'Co tydzień'), ('monthly', 'Co miesiąc'), ('custom', 'Niestandardowo')], max_length=10)),
                ('time', models.TimeField(help_text='Czas wykonania (HH:MM)')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Dzień miesiąca (1-31)', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('retain_count', models.IntegerField(default=10, help_text='Ile ostatnich backupów zachować')),
                ('email_notification', models.BooleanField(default=False)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_tasks', to='backup_manager.databaseserver')),
            ],
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Sukces'), ('error', 'Błąd'), ('pending', 'W trakcie')], default='pending', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.databaseserver')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup_manager.backuptask')),
            ],
        ),
    ]
