# Generated by Django 5.2.1 on 2025-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0003_backuptask_backuphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='database_name',
            field=models.CharField(blank=True, help_text='Nazwa konkretnej bazy do backupu. Pozostaw puste dla wszystkich baz.', max_length=100, null=True),
        ),
    ]
