# Generated by Django 5.2.1 on 2025-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0004_databaseserver_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistory',
            name='description',
            field=models.TextField(blank=True, help_text='Opis operacji lub dodatkowe informacje'),
        ),
    ]
