# Generated by Django 5.2.1 on 2025-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0008_appsettings_storageconfig_backuptask_storage_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuptask',
            name='gdrive_credentials_file',
            field=models.FileField(blank=True, help_text='JSON credentials file', null=True, upload_to='gdrive_creds/'),
        ),
        migrations.AddField(
            model_name='backuptask',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, help_text='Google Drive folder ID (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backuptask',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local Storage'), ('ftp', 'FTP Server'), ('sftp', 'SFTP Server'), ('gdrive', 'Google Drive')], default='local', max_length=10),
        ),
    ]
