# Generated by Django 5.2.1 on 2025-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0009_backuptask_gdrive_credentials_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageconfig',
            name='gdrive_credentials_file',
            field=models.FileField(blank=True, help_text='JSON credentials file', null=True, upload_to='gdrive_creds/'),
        ),
        migrations.AddField(
            model_name='storageconfig',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, help_text='Google Drive folder ID (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storageconfig',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local Storage'), ('ftp', 'FTP Server'), ('sftp', 'SFTP Server'), ('gdrive', 'Google Drive')], default='local', max_length=10),
        ),
    ]
