# Generated by Django 5.2.1 on 2025-05-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0011_alter_databaseserver_connection_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseserver',
            name='connection_type',
            field=models.CharField(choices=[('direct', 'MariaDB/MySQL (TCP/IP)'), ('ssh', 'MariaDB/MySQL (SSH Tunnel)'), ('direct_postgresql', 'PostgreSQL (TCP/IP)'), ('ssh_postgresql', 'PostgreSQL (SSH Tunnel)')], max_length=20),
        ),
    ]
